os: osx
podfile: flutter/ios/Podfile

env:
  global:
  - SDK_ROOT="$HOME/sdk"
  - PATH="$PATH:$SDK_ROOT/flutter/bin"

branches:
  only:
  - master

cache:
  bundler: true
  cocoapods: true

script:
- bundle exec pod setup

- git clone --depth=1 --branch=beta https://github.com/flutter/flutter.git "${SDK_ROOT?}/flutter"
- flutter doctor

# Do not require signing of iOS applications (key is not available on Travis)
- sed -i ''
  -e 's/"CODE_SIGN_IDENTITY.*/CODE_SIGNING_REQUIRED = NO;/g'
  flutter/ios/Runner.xcodeproj/project.pbxproj

- ( cd flutter && flutter build ios --debug )

# Check that there are no modifications (except the ones we did)
- git checkout
  flutter/ios/Runner.xcodeproj/project.pbxproj
  .bundle/config
- git status
- git diff
- test -z "$(git status --porcelain)"
