version: 2

defaults: &defaults
  docker:
  - image: dasfoo/firebase:latest
  environment:
  - ANDROID_HOME: /root/android-sdk
  - TERM: dumb
  # https://docs.gradle.org/current/userguide/gradle_daemon.html#when_should_i_not_use_the_gradle_daemon
  # "It is recommend to disable the Daemon for Continuous Integration and build server environments."
  - GRADLE_OPTS: -Dorg.gradle.daemon=false

gcloud_install_command: &gcloud_install_command
  name: "Install GCloud, download & activate authentication keys"
  command: |
    # We use this account to access both Google Play account and GCS.
    # The former requires it to be in "app" subdirectory.
    echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > app/play-store-service-account.json
    gcloud auth activate-service-account --key-file app/play-store-service-account.json
    mkdir -p ~/.android
    gsutil cp gs://dasfoo-keystore/debug.keystore ~/.android/
    gsutil cp gs://dasfoo-keystore/delern.jks app/

jobs:
  checkout:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: "Prepare checked out Git repository"
        command: |
          # --invert-grep appeared only in Git 2.4
          if git log --format=%H "origin/master.." |
              grep -x -v -f <(git log --format=%H "origin/master.." -E --grep '^relnote: (.*[.]|none[.]?)$'); then
            echo "Found commits without (or with invalid) Release Notes, aborting"
            exit 1
          fi
          git submodule sync
          git submodule update --init
          # We count tags to compute a version number; make sure renamed tags
          # (aka removed and re-added) do not count twice.
          git tag -l | xargs git tag -d
          git fetch --tags
    - persist_to_workspace:
        root: ..
        paths:
        - project

  dependencies:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..

    - run: ci-dependencies hash
    - restore_cache:
        keys:
        - v11-android-{{ arch }}-{{ .Branch }}-{{ checksum "../.cache/dependencies.hash" }}
        - v11-android-{{ arch }}-{{ .Branch }}-
        - v11-android-{{ arch }}-master-

    - run:
        name: "Install dependencies"
        command: |
          ci-dependencies explode
          mkdir -p "${ANDROID_HOME?}/licenses"
          # This is just a hash sum of the license agreements accepted.
          # Take this text from the Android SDK directory on your machine.
          echo 8933bad161af4178b1185d1a37fbf41ea5269c55 >>"${ANDROID_HOME?}/licenses/android-sdk-license"
          echo d56f5187479451eabf01fb78af6dfcb131a6481e >>"${ANDROID_HOME?}/licenses/android-sdk-license"
          ci-dependencies install collect

    - save_cache:
        # Use different keys because caches are immutable.
        key: v11-android-{{ arch }}-{{ .Branch }}-{{ checksum "../.cache/dependencies.hash" }}
        paths:
        - ~/.cache/dependencies

    - persist_to_workspace:
        root: ..
        paths:
        - project
        - .cache/dependencies

  unit-tests:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..
    - run: ci-dependencies explode

    - run:
        name: "Lint, assemble and run unit tests"
        no_output_timeout: "35m"
        command: |
          # Check formatting
          ci-lint
          git diff --stat --exit-code
          # Run lint over debug (rather than instrumented) to allow the tools to access non-optimized
          # class data.
          ./gradlew \
            --continue \
            :app:checkQualityDebug \
            :core:checkQualityMain \
            :app:testDebugUnitTest \
            :core:test \
            --quiet \
            --console=plain
          # Assemble instrumented to check ProGuard configuration and warnings.
          ./gradlew \
            --continue \
            :app:assembleInstrumented \
            :app:assembleInstrumentedAndroidTest \
            --quiet \
            --console=plain >/dev/null
          # Lint Polymer files
          # TODO(dotdoom): ci-lint-html
          ( cd firebase/www && polymer lint && polymer build )

    - store_test_results:
        path: core/build/test-results
    - store_test_results:
        path: app/build/test-results

    - run:
        name: "Re-run unit tests with INFO level"
        command: |
          ./gradlew \
            --info \
            :app:testDebugUnitTest \
            :core:test \
            --console=plain
        when: on_fail

    - persist_to_workspace:
        root: ..
        paths:
        # Persist project so that coverage results make it to codecov.
        - project

  deploy-firebase-debug:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..
    - run: ci-dependencies explode
    - run:
        <<: *gcloud_install_command

    - run:
        working_directory: ~/project/firebase
        name: "Deploy Firebase database rules, functions, hosting to DEBUG"
        environment:
          PROJECT: delern-debug
        command: npm run deploy

  instrumented-coverage:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..
    - run: ci-dependencies explode
    - run:
        <<: *gcloud_install_command

    - run:
        name: "Run instrumented tests without ProGuard (for coverage)"
        no_output_timeout: "35m"
        command: |
          ./gradlew \
            -PcoverageRun \
            assembleInstrumented \
            assembleInstrumentedAndroidTest \
            --console=plain
          # https://circleci.com/docs/firebase-test-lab/
          gcloud --project=delern-debug firebase test android run \
            --device model=Nexus5X,version=26 \
            --timeout 30m \
            --app app/build/outputs/apk/instrumented/app-instrumented.apk \
            --test app/build/outputs/apk/androidTest/instrumented/app-instrumented-androidTest.apk \
            --environment-variables coverage=true,coverageFile=/sdcard/coverage/coverage.ec \
            --directories-to-pull /sdcard/coverage \
            --results-bucket delern-test-results \
            --results-dir "circle-${CIRCLE_BUILD_NUM}"
          gsutil cp "gs://delern-test-results/circle-${CIRCLE_BUILD_NUM}/*/artifacts/coverage.ec" \
            app/build/outputs/code-coverage/connected/coverage.ec
          ./gradlew -PcoverageRun -x app:connectedInstrumentedAndroidTest app:createInstrumentedAndroidTestCoverageReport
          # The code in "app" can only be covered by Android on-device tests,
          # therefore PR builds will always report false negatives.
          ./gradlew \
            core:jacocoTestReport \
            app:jacocoTestDebugUnitTestReport \
            --console=plain
          bash <(curl -s https://codecov.io/bash)

    - store_artifacts:
        path: app/build/outputs
    - store_artifacts:
        path: app/build/reports

    - persist_to_workspace:
        root: ..
        paths:
        # Persist test results to export to CircleCI.
        - project

  instrumented-proguard:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..
    - run: ci-dependencies explode
    - run:
        <<: *gcloud_install_command

    - run:
        name: "Run instrumented tests with ProGuard"
        no_output_timeout: "35m"
        command: |
          ./gradlew \
            assembleInstrumented \
            assembleInstrumentedAndroidTest \
            --console=plain
          # https://circleci.com/docs/firebase-test-lab/
          gcloud --project=delern-debug firebase test android run \
            --device model=m0,version=18 \
            --timeout 30m \
            --app app/build/outputs/apk/instrumented/app-instrumented.apk \
            --test app/build/outputs/apk/androidTest/instrumented/app-instrumented-androidTest.apk

    - store_artifacts:
        path: app/build/outputs
    - store_artifacts:
        path: app/build/reports

  deploy-firebase-release:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..
    - run: ci-dependencies explode
    - run:
        <<: *gcloud_install_command

    - run:
        working_directory: ~/project/firebase
        name: "Deploy Firebase database rules, functions, hosting to RELEASE"
        environment:
          PROJECT: delern-e1b33
        command: npm run deploy

    - run:
        name: "Assemble release APK (to store in artifacts)"
        command: ./gradlew clean lintRelease assembleRelease

    - store_artifacts:
        path: app/build/outputs

  google-play:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ..
    - run: ci-dependencies explode
    - run:
        <<: *gcloud_install_command

    - run:
        name: "Run instrumented tests with ProGuard (on a hardware device)"
        no_output_timeout: "35m"
        command: |
          ./gradlew \
            assembleInstrumented \
            assembleInstrumentedAndroidTest \
            --console=plain
          gcloud --project=delern-debug firebase test android run \
            --timeout 30m \
            --app app/build/outputs/apk/instrumented/app-instrumented.apk \
            --test app/build/outputs/apk/androidTest/instrumented/app-instrumented-androidTest.apk
    - run:
        name: "Upload release APK to Google Play"
        command: |
          # Build relnote.
          previous_tag="$(git tag --sort=version:refname | grep -F -v -x -- "${CIRCLE_TAG?}" | tail -1)"
          git log "${previous_tag?}.." --format=%B | \
            cat <(echo "relnote: ${CIRCLE_TAG}") - |
            grep '^relnote: ' | \
            grep -E -v -x 'relnote: none[.]?' | \
            cut -b10- | \
            awk '!a[$0]++' >app/src/main/play/en-US/whatsnew
          # Publish to Google Play (this also automatically runs Robo tests).
          ./gradlew lintRelease publishRelease --console=plain

    - store_artifacts:
        path: app/src/main/play
    - store_artifacts:
        path: app/build/outputs
    - store_artifacts:
        path: app/build/reports

workflows:
  version: 2

  build-and-release:
    jobs:
    - checkout:
        filters: &release_tags
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
    - dependencies:
        requires:
        - checkout
        filters: *release_tags
    - unit-tests:
        requires:
        - checkout
        - dependencies
        filters: *release_tags
    - deploy-firebase-debug:
        requires:
        - checkout
        - dependencies
        filters:
          <<: *release_tags
          branches:
            only: master
    - instrumented-coverage:
        requires:
        - checkout
        - dependencies
        - deploy-firebase-debug
        filters:
          branches:
            only: master
    - instrumented-proguard:
        requires:
        - checkout
        - dependencies
        - deploy-firebase-debug
        filters:
          branches:
            only: master
    - deploy-firebase-release:
        requires:
        - checkout
        - dependencies
        - deploy-firebase-debug
        - instrumented-proguard
        filters:
          <<: *release_tags
          branches:
            only: master
    - google-play:
        requires:
        - checkout
        - dependencies
        - deploy-firebase-debug
        - deploy-firebase-release
        - instrumented-proguard
        filters:
          <<: *release_tags
          branches:
            ignore: /.*/
