version: 2
jobs:
  build:
    working_directory: ~/delern
    docker:
    - image: openjdk:8
    environment:
    - ANDROID_HOME: /opt/android-sdk-linux
    - TERM: dumb
    - IDEA_VERSION: IC-2017.1.4-no-jdk
    steps:
    - checkout
    - run:
        name: "Prepare checked out Git repository"
        command: |
          # --invert-grep appeared only in Git 2.4
          if git log --format=%H "origin/master.." |
              grep -x -v -f <(git log --format=%H "origin/master.." --grep '^relnote: '); then
            echo "Found commits without Release Notes, aborting"
            exit 1
          fi
          git submodule sync
          git submodule update --init
          # We count tags to compute a version number; make sure renamed tags
          # (aka removed and re-added) do not count twice.
          git tag -l | xargs git tag -d
          git fetch --tags

    - restore_cache:
        keys:
        - v3-android-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
        - v3-android-{{ .Branch }}-{{ checksum "build.gradle" }}-
        - v3-android-{{ .Branch }}-
        - v3-android-master-

    - run:
        name: "Install Android SDK"
        command: |
          mkdir -p "${ANDROID_HOME?}/licenses"
          # This is just a hash sum of the license agreements accepted.
          # Take this text from the Android SDK directory on your machine.
          echo 8933bad161af4178b1185d1a37fbf41ea5269c55 >"${ANDROID_HOME?}/licenses/android-sdk-license"
          ./gradlew dependencies --status

    - run:
        name: "Lint, assemble and run unit tests"
        command: |
          # Run lint over debug (rather than instrumented) to allow the tools to access non-optimized
          # class data. Assemble instrumented to check ProGuard configuration and warnings.
          ./gradlew \
            -PisolatedRun \
            --continue \
            lintDebug \
            :app:testDebugUnitTest \
            :core:testLocalFirebaseUnitTest \
            :app:assembleInstrumented \
            --console=plain

    - run:
        name: "Re-run unit tests with INFO level"
        command: |
          ./gradlew \
            -PisolatedRun \
            --info \
            :app:testDebugUnitTest \
            :core:testLocalFirebaseUnitTest \
            --console=plain
        when: on_fail

    # TODO(dotdoom): collect coverage from other targets, too
    - run:
        name: "Generate and upload test coverage"
        command: |
          ./gradlew core:jacocoTestLocalFirebaseUnitTestReport --console=plain
          bash <(curl -s https://codecov.io/bash)

    # Some packages are installed only during the lint/assemble step, we need to cache them as well.
    - save_cache:
        # Use different keys because caches are immutable.
        key: v3-android-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
        paths:
        - ~/.gradle
        # TODO(dotdoom): use environment variables once they are supported
        - /opt/android-sdk-linux

    - restore_cache:
        keys:
        # TODO(dotdoom): use environment variable once it's supported.
        #                Currently only CircleCI built-in variables are supported.
        - v1-idea

    - run:
        name: "Install IDEA"
        command: |
          if [ ! -d ~/idea ]; then
            mkdir ~/idea
            curl -sSL "https://download.jetbrains.com/idea/idea${IDEA_VERSION?}.tar.gz" |
                tar -C ~/idea -x -z
            mv ~/idea/* ~/idea/ide
          fi

    - save_cache:
        key: v1-idea
        paths:
        - ~/idea

    - run:
        name: "Check code formatting"
        command: |
          ~/idea/ide/bin/format.sh -m '*.java' -r */src
          git diff --stat --exit-code

    - deploy:
        name: "Install Cloud SDK, run instrumented tests"
        # https://cloud.google.com/sdk/downloads#apt-get
        command: |
          if [ -n "${CIRCLE_TAG}" -o "${CIRCLE_BRANCH}" = "master" ]; then
            # These two packages are normally already available, but we deal with some extremely minimalistic Docker image.
            apt update
            apt install -y lsb-release apt-transport-https

            echo "deb https://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" \
              >>/etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            apt update
            apt install -y google-cloud-sdk

            # We use this account to access both Google Play account and GCS.
            # The former requires it to be in "app" subdirectory.
            echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > app/play-store-service-account.json
            gcloud auth activate-service-account --key-file app/play-store-service-account.json
            gsutil cp gs://dasfoo-keystore/debug.keystore ~/.android
            gsutil cp gs://dasfoo-keystore/fabric.properties app
            # https://circleci.com/docs/firebase-test-lab/
            ./gradlew \
              assembleInstrumented \
              assembleInstrumentedAndroidTest \
              --console=plain
            # Run instrumented tests.
            gcloud --project=delern-debug firebase test android run \
              --app app/build/outputs/apk/instrumented/app-instrumented.apk \
              --test app/build/outputs/apk/androidTest/instrumented/app-instrumented-androidTest.apk \
              --results-bucket delern-test-results
          fi

    - deploy:
        name: "Build signed Release binary, run instrumented tests, publish to Google Play"
        command: |
          if [ -n "${CIRCLE_TAG}" ]; then
            previous_tag="$(git tag --sort=version:refname | grep -F -v -x -- "${CIRCLE_TAG?}" | tail -1)"
            git log "${previous_tag?}.." --format=%B | \
              grep '^relnote: ' | \
              grep -v -x 'relnote: none' | \
              cut -b10- | \
              cat <(echo "${CIRCLE_TAG}") - >app/src/main/play/en-US/whatsnew
            gsutil cp gs://dasfoo-keystore/delern.jks app
            # Publish to Google Play (this also automatically runs Robo tests).
            ./gradlew lintRelease publishRelease --console=plain
          fi

    - store_test_results:
        path: app/build/test-results
    - store_test_results:
        path: core/build/test-results
    - store_artifacts:
        path: app/build/outputs
    - store_artifacts:
        path: app/build/reports
    - store_artifacts:
        path: app/src/main/play

workflows:
  version: 2
  build-workflow:
    jobs:
    - build:
        filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
