name: delern_flutter
description: Spaced repetition learning system (Flutter version)

dependencies:
  sentry:
    # actively worked on, but rarely released.
    git: git://github.com/flutter/sentry.git

  # Do not upgrade these packages unless you need it.
  # Bumping these versions may bump minimum Play Services version required to
  # run the app, resulting in older phones being unsupported.
  firebase_auth: 0.5.11
  firebase_database: 1.0.1
  google_sign_in: 3.0.4
  device_info: ^0.2.1
  package_info: ^0.3.0
  url_launcher: 3.0.3

  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter
  intl_translation: 0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  http: ^0.11.3+16

  share: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/ic_launcher.png
  - images/delern.png
  - images/google_sign_in.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
