name: delern_flutter
description: Spaced repetition learning system (Flutter version)

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
# TODO(dotdoom): uncomment after https://github.com/flutter/flutter/issues/22788
#version: 1.0.0+1

dependencies:
  device_info: ^0.3.0
  package_info: ^0.3.2
  url_launcher: ^3.0.3
  flutter_markdown: ^0.2.0
  http: ^0.11.3
  share: ^0.5.2
  sentry: ^2.1.1
  shared_preferences: ^0.4.3
  intro_views_flutter: ^2.2.4
  quiver: '>=2.0.0 <3.0.0'

  firebase_auth: ^0.6.6
  firebase_analytics: ^1.0.6
  firebase_database: ^1.0.5
  firebase_messaging: ^2.1.0
  google_sign_in: ^3.2.4

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  intl_translation: ^0.17.0
  mockito: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/ic_launcher.png
  - images/google_sign_in.png
  - images/anonymous.jpg
  - images/card_sharing.png
  - images/child_learning.png
  - images/deck_creation.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
